apiVersion: v1
kind: Pod
metadata:
  name: pod-viewer
  labels:
    app: pod-viewer
spec:
  serviceAccountName: pod-viewer
  containers:
  - name: pod-viewer
    image: esl/pod-viewer
    imagePullPolicy: Always
